### ISSUE TITLE
Design Docs Checklist

### ISSUE THREAD

**Issue by siascone** [Naim08/DiscordClone#1]
# Wiki Home Page
- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
  - [x] each wiki page is listed in bullet points
  - [x] all links route the correct page

## Comments

---

# MVP List
- [x] Should have 7 MVPs.
  - [x] 3 of those are User Auth, Heroku, and Production README.
  - [x] The other 4 are from the [Approved Apps List](https://github.com/appacademy/cohort-resources/blob/master/full_stack_projects/aa_approved_full_stack_projects.md) or your PM will have clarified them with you
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
  - [x] MVPs are listed in an ordered list
  - [x] Each MVP is broken down into bullet points

## Comments

---

# Database Schema
- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
  - [x] primary key
  - [x] not null
  - [x] unique
  - [x] indexed
  - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
 - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
  - [x] schema is written in a table format
  - [x] the table's name are lowercased, snake_cased and `back_ticked`
  - [x] the table header column names are bolded
  - [x] columns names are lowercased and snaked_cased and `back_ticked`

## Comments

---

# Sample State
- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
  - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
  - [x] Top level slices
    - [x] `entities`
    - [x] `session`
    - [x] `errors` (here or in `ui`)
    - [x] `ui` (if needed)
  - [x] Should NOT have nested slices, aka `comments` inside of `posts`
   + Some info from other tables is ok, for instance:
    + the author username and imageurl for a post. basically any info that the user can't change
    + like count and a boolean on whether the user likes the post instead of a likes slice

## Comments

---

# Backend Routes
- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
  + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

## Comments

---

# Frontend Routes
- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
  - [x] Routes are displayed with `inline coding text` (backticks)

## Comments

**Comment by siascone** [comment]
Initial Review:

Currently due design docs of MVP Feature List, Schema are missing. Please submit those asap.

**Comment by Naim08** [comment]
updated wiki page

**Comment by siascone** [comment]
Wiki Home Page:
- Looking good. 
- Add a placeholder link for your eventual live site

MVP List:
- What you have listed as User Management is User Auth so that featuer is already listed. 
- The four core features you will be building are what we discussed upon approval. Your full features list should be in order
  - 1 Hosting on Render
  - 2 User Authorization
  - 3 Servers CRUD
  - 4 Channels CRUD
  - 5 Messaging in Channels CRUD
  - 6 Direct Messages CRUD
  - 7 Production README
- Add estimated dates to completion for each feature

Schema:
- You don't need to list the activeStorage related schemas but nice job all the same
- Each table should have bullets indicating associations and indexing
- Each table should indicate foreign_key and primary_keys where appropriate
- table names and column names should be lower cased and backticked ex: `table_name` `column_name`
- You only need the tables for your planned features. Once you revise your feature list you can revise your table list.

Check out [BlueBird Wiki](https://github.com/appacademy/bluebird/wiki) for reference on each of these docs.

**Comment by Naim08** [comment]
Updated schema and state

**Comment by siascone** [comment]
Wiki Home Page:
- Complete

MVP List:
- Complete

Schema:
- Associations don't need a subheading, can just be listed below table.
- Table  and columns need some backtick formatting. See [BlueBird Wiki Schema](https://github.com/appacademy/bluebird/wiki/schema) for reference

State Shape:
- Complete

**Comment by Naim08** [comment]
Backend and frontend routes wiki page updated.

**Comment by siascone** [comment]
Wiki Home
- Complete

Feature List
- Complete

Schema
- Complete

Sample State
- Complete

Frontend Routes
- Complete

Backend Routes
- Ask yourself if you absolutely need nested routes. Most of the time this can be handled on the frontend by the structure of your redux store.

**Comment by Naim08** [comment]
Removed superfluous routes (around 4 of them)

**Comment by siascone** [comment]
All looks good!
